### ISSUE TITLE
jsdelivr 캐싱으로 인한 패치 파일 지연 갱신 문제

### ISSUE THREAD

**Issue by refracta** [StableFluffy/bg3_paks#3]
![image](https://github.com/StableFluffy/bg3_paks/assets/58779799/60026320-4a4d-4bac-b220-67da337b7603)
9일 4시경 GitHub와 CDN 이용하여 받은 패치 코어 파일 비교

현재 패치 사이트에서 CDN을 이용하여 파일을 받고 있는데, 깃헙에 갱신된 지 한참 후에 갱신이 이루어지는 것 같습니다 (쿼리로 현재 시간 timestamp를 보내도 마지막 갱신 파일이 제공되지 않음)

백엔드 단에서 자체적인 캐싱을 해서 제공하거나

리액트 빌드 파일을 이 저장소에 올린 뒤에 github.io로 배포하여, 본 저장소 파일에 바로 접근하는 방식은 어떨까요

캐시 지연으로 혼선을 빚는 사람들이 많은 것 같아 제보드립니다

**Comment by refracta** [comment]
https://github.com/jsdelivr/jsdelivr#github
해당 문서 보고 실험해봤는데

`https://cdn.jsdelivr.net/gh/StableFluffy/bg3_paks@latest/paks/deepl_ai_korean_rating_we.zip`
는 예전 버전으로 받아지는데
`https://cdn.jsdelivr.net/gh/StableFluffy/bg3_paks@98e9eb792f636e081fc5ea3e5b578308d100e175/paks/deepl_ai_korean_rating_we.zip`
해당 커밋 버전 명시하니, 가장 마지막 것으로 받아지네요
이 방식이 더 나을 것 같습니다

`https://api.github.com/repos/StableFluffy/bg3_paks/commits/main` GitHub API 이용해서 
```js
const hash = JSON.parse(await fetch('https://api.github.com/repos/StableFluffy/bg3_paks/commits/main').then(r => r.text())).sha;
const url = `https://cdn.jsdelivr.net/gh/StableFluffy/bg3_paks@${hash}/paks/${name}.zip`;
```
이렇게 하면 자동으로 가장 최신 것으로 적용될 것 같습니다.
*. 해당 API는 timestamp나 별도 처리 없이도 실시간 유지되는 것 확인했습니다

**Comment by StableFluffy** [comment]
반영 하겠습니다.
