### ISSUE TITLE
정말 감사드립니다!

### ISSUE THREAD

**Issue by tk8812** [StableFluffy/bg3_paks#5]
공식 한글패치가 갑자기 나와 왈도팀의 노력이 사라지는 듯하여  안타까운 마음에 

그동안 패치를 통해 재미있게 플레이하였던 감사한 마음을 전달하고자

여기에 글을 남기게 되었습니다.

그동안 정말 수고 많으셨습니다. 왈도팀의 헌신적인 노력으로 정말 재밌게 플레이 할 수 있었습니다!

다시 한번 감사드립니다!

**Comment by StableFluffy** [comment]
재미있게 즐겨주셨다니 기쁩니다. 갑자기 한글패치가 나와버리는 바람에 약간은 당혹스럽지만 100% 한글패치가 나와서 기쁜마음입니다.
이번 번역 참여하며 얻은 기술로 발더스게이트 외에도 번역 필요한거나 커뮤니티에 기여할거 있으면 깃헙 이슈나 기타 등등 통해서 연락남겨주시면 도울생각입니다.
즐거웠습니다.
